Testing pullrequest
ROMELIKE/Larangular pull request #2
Opened 2017-05-09 10:41 UTC by ROMELIKE

2017-05-10 10:25 UTC, quanghoan commented on app/Http/Controllers/MemberController.php
> +        dd($action->message);
pls remove dd();

2017-05-10 10:25 UTC, quanghoan commented on public/admin/js/AngularJS/main.js
> +                console.log(response);
pls remove none-fuction code such as console.log(), dd(), var_dump()

2017-05-12 02:49 UTC, 4c0n requested changes

2017-05-12 02:49 UTC, 4c0n commented on app/Http/Controllers/MemberController.php
> +                AND in_array($extAddition, ['png', 'jpg', 'jpeg', 'gif'])
Please use && instead of AND

2017-05-12 02:49 UTC, 4c0n commented on app/Http/Controllers/MemberController.php
> +//                    dd($request->avatar->getSize());
Please remove this line.

2017-05-12 02:49 UTC, 4c0n commented on app/Http/Controllers/MemberController.php
> +                    if($mimeType!='inode/x-empty'){
This is not PSR-2, please run phpcs before pushing.

2017-05-12 02:49 UTC, 4c0n commented on app/Http/Requests/MemberRequest.php
> +            'address.not_in'=>'address is nacessary ( < 300)',
nacessary -> necessary

2017-05-12 02:49 UTC, 4c0n commented on database/factories/ModelFactory.php
>      static $password;
Please do not use static variables.

2017-05-12 02:49 UTC, 4c0n commented on public/admin/js/AngularJS/main.js
> +            // console.log($scope.file);
Please remove console.log(), dd() and var_dump() lines. Debugging lines should not be committed.

2017-05-12 02:49 UTC, 4c0n commented on tests/Feature/MemberControllerTest.php
> +        $member = factory(MemberModel::class)->create();
$member does not seem to be used. Please use it or remove it.

2017-05-12 02:49 UTC, 4c0n commented on tests/Feature/WrongMemberControllerTest.php
> +        $this->assertEquals(302, $response->status());
If the controller also gives a JSON response, please assert the response message.

2017-05-12 03:52 UTC, merged